### ISSUE TITLE
Issues with updating cart

### ISSUE THREAD

**Issue by ps-PKrueger** [cyberwombat/woocommerce-fastspring-payment-gateway#6] opened 2018-05-30 14:44 UTC
There is an issue with updating the cart for item quantities before checking out.  For some reason, the gateway is not retrieving an updated value for the items in the cart. It is causing something strange to happen in the fastspring checkout window.

Here are some images showing the differences:

![ex1](https://user-images.githubusercontent.com/12850324/40727517-a7a9330e-63ed-11e8-8a8d-cb4adf7566d7.png)

![ex2](https://user-images.githubusercontent.com/12850324/40727554-bb5612e6-63ed-11e8-9a06-da5b44112417.png)

To replicate:
1. Add several items to the cart. (subscriptions)
2. Go to the cart and change the values of the subscriptions up and down.
3. Update the cart.
4. Go to checkout.
5. Checkout, and the value in fastspring will be different than the value in the Woocommerce cart and checkout page.

Thoughts?

**Comment by ps-PKrueger** [comment] 2018-05-31 05:35
I have now verified that this is not just an issue with updating the cart, it has to do with any order that has quantities greater than 1.

If I add more than one of an item to the cart before checking out, I get a weird price value in the Fastspring window.

I am also not using coupons, or other discounting mechanisms.

**Comment by ps-PKrueger** [comment] 2018-05-31 09:08
In a further update to this issue, it looks like the gateway is sending the value = price / number of items, and not price * number of items. At least, that is consistent with what I am getting.

My Price: $25

Fastspring Checkout  

Qty 1 - $25.00
Qty 2 - $12.50
Qty 3 - $8.33

**Comment by cyberwombat** [comment] 2018-06-03 15:54
Thank you. I patched things temporarily - indeed the quantity was applied wrong but I am running into issues with rounding errors. The gist of the problem is that FS doesn't handle discounts so I have to adjust item prices to create a fake discount but this creates issues with rounding (i.e. 3 * $20 with a $10 discount yields $50.01 in FS). I will explore creating a fake discount item if FS lets me do negatives but I am not sure yet. I will leave this issue open to remind me to address that.

**Comment by ps-PKrueger** [comment] 2018-06-04 01:17
I am solving this by not allowing coupons on Woo, only on Fastspring checkout. That way, they have to calculate the discounts, and no rounding error will be produced. It is too bad that fastspring won't let you reference a coupon code on their site, and apply that.

**Comment by ps-PKrueger** [comment] 2018-06-11 14:32
1.1.2 seems to have solved the dividing error, but now there is an error when updating the cart.  This happens when I am in the cart, and I have selected multiple items with quantities. When I first go to the checkout page, add my info and click the "Place Order" button, I get a price value in the pop up that is for quantity 1 of each item in the cart. When I cancel and click the "Place Order" button again, it updates to the correct value for all items and quantities in the cart.

If I go back to the cart, it resets with this same behavior, so I think that it may be pulling incorrect quantity information from the cart. I added a picture so that you could see the different prices.

![these prices dont match](https://user-images.githubusercontent.com/12850324/41237831-25b3346e-6d5a-11e8-972f-d09102740de9.png)

**Comment by ps-PKrueger** [comment] 2018-06-18 14:27
Moved the above issue to a new issue, as I am not sure that they are related in the plugin.

**Comment by cyberwombat** [comment] 2018-06-18 21:46
Thanks for update. Closing this issue and addressing the other asap.

**Closed as completed by cyberwombat** 2018-06-18 21:46 UTC
